In [ ]:
# NIM/Nama  : 19623005/Carlo Angkisan
# Tanggal   : 16 November 2023
# Deskripsi : Problem 1
              # 1. Menghitung dan menampilkan banyaknya rumah pada masing-masing neighbourhood group
              # 2. Menampilkan rumah dengan jumlah review di aplikasi terbanyak selama 12 bulan
              # 3. Menampilkan 5 data rumah dengan jumlah malam penyewaan minimum terendah
              # 4. Menampilkan Rumah yang dimiliki oleh Jayce
              # 5. Menampilkan koefisien korelasi antara banyaknya review tiap bulan dengan jumlah malam penyewaan minimum dan menjelaskan hubungan korelasi keduanya

In [1]:
# Mengimport library yang dibutuhkan
import pandas as pd

# Membaca data P05-03.csv
df = pd.read_csv('P05-03.csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,38105126,Loft 2 pax near Haw Par / Pasir Panjang. Free ...,278109833,Belle,Central Region,Queenstown,1.27973,103.78751,Entire home/apt,100,3,0,NaN,NaN,31,61
7903,38108273,3bedroom luxury at Orchard,238891646,Neha,Central Region,Tanglin,1.29269,103.82623,Entire home/apt,550,6,0,NaN,NaN,34,365
7904,38109336,[ Farrer Park ] New City Fringe CBD Mins to MRT,281448565,Mindy,Central Region,Kallang,1.31286,103.85996,Private room,58,30,0,NaN,NaN,3,173
7905,38110493,Cheap Master Room in Central of Singapore,243835202,Huang,Central Region,River Valley,1.29543,103.83801,Private room,56,14,0,NaN,NaN,2,30
7906,38112762,Amazing room with private bathroom walk to Orc...,28788520,Terence,Central Region,River Valley,1.29672,103.83325,Private room,65,90,0,NaN,NaN,7,365

In [6]:
# 1. Menghitung dan menampilkan banyaknya rumah pada masing-masing neighbourhood group
print(df['neighbourhood_group'].value_counts())

neighbourhood_group
Central Region       6309
West Region           540
East Region           508
North-East Region     346
North Region          204
Name: count, dtype: int64

In [5]:
# 2. Menampilkan rumah dengan jumlah review di aplikasi terbanyak selama 12 bulan
print(f"Rumah dengan jumlah review di aplikasi terbanyak selama 12 bulan adalah {df.loc[df['number_of_reviews'].idxmax()]['name']}")

Rumah dengan jumlah review di aplikasi terbanyak selama 12 bulan adalah Luxuriously Spacious Studio Apt.

In [9]:
# 3. Menampilkan 5 data rumah dengan jumlah malam penyewaan minimum terendah
df.sort_values(['minimum_nights'], ascending=True)[:5]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2766,19751695,Newly Refurbished Private Room @ Sembawang MRT,15035611,Anna,North Region,Sembawang,1.45111,103.82765,Private room,87,1,7,2017-12-16,0.28,1,0
6674,34244096,B1 • Minimalistic Room 5mins Train To MBS And ...,3234859,Sk,Central Region,Rochor,1.30324,103.86057,Private room,110,1,8,2019-08-17,2.31,9,138
2183,16640229,Brand New Cosy 2-Bedroom Apartment,109931020,Nyah,Central Region,Marine Parade,1.30101,103.89784,Entire home/apt,269,1,1,2017-01-20,0.03,1,0
4640,28116713,Terrace House @ Thomson Village,25375339,ｼﾝ,Central Region,Bishan,1.35389,103.83230,Entire home/apt,500,1,0,NaN,NaN,9,365
4639,28116308,Masteroom (bath) @ Terrace House @ Thomson Vil...,25375339,ｼﾝ,Central Region,Bishan,1.35266,103.83360,Private room,81,1,1,2018-10-03,0.09,9,362

In [10]:
# 4. Menampilkan Rumah yang dimiliki oleh Jayce
df.loc[df['host_name']=='Jayce']

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1890,15351390,Private Room near Paya Lebar&Dakota,78386666,Jayce,Central Region,Geylang,1.31150,103.89015,Private room,62,2,0,NaN,NaN,6,0
1950,15712633,Private Room near Paya Lebar MRT,78386666,Jayce,Central Region,Geylang,1.31476,103.88913,Private room,53,1,15,2018-10-03,0.45,6,0
2007,16027385,Private Common Room at near Paya Lebar MRT,78386666,Jayce,Central Region,Geylang,1.31728,103.88995,Private room,56,2,5,2018-04-30,0.17,6,0
2351,17677387,Private Master Room with attach bathroom,78386666,Jayce,Central Region,Geylang,1.31650,103.88944,Private room,56,1,2,2018-02-04,0.10,6,0
2513,18443344,Private Master Room w/Own Bathroom at paya lebar,78386666,Jayce,Central Region,Geylang,1.31449,103.89031,Private room,56,2,5,2019-01-01,0.29,6,0
2901,20446077,The condo common room at dakota mrt,78386666,Jayce,Central Region,Geylang,1.31193,103.88905,Private room,49,2,1,2018-01-23,0.05,6,0

In [11]:
# 5. Menampilkan koefisien korelasi antara banyaknya review tiap bulan dengan jumlah malam penyewaan minimum. 
df['reviews_per_month'].corr(df['minimum_nights'])

-0.13946933876931425

Berdasarkan koefisien korelasi tersebut, dapat disimpulkan bahwa banyaknya review tiap bulan dengan jumlah malam penyewaan minimum tidak berkorelasi karena nilai koefisien tersebut mendekati 0.